from skellysubs.system.logging_configuration.configure_logging import configure_logging
from skellysubs.system.logging_configuration.logger_builder import LogLevels

configure_logging(LogLevels.TRACE)