languages:
  ENGLISH:
    romanization_method: NONE
    annotation_config:
      font_path: "fonts/ARIAL.TTF"
      font_size_ratio: 0.016
      buffer_size: 100
      color: [ 27, 158, 119 ]
      language_start_y_offset: 0.5
    background:
      family_tree: [ "Indo-European", "Germanic", "West Germanic" ]
      alphabet: "Latin"
      sample_text: "The quick brown fox jumps over the lazy dog."

  SPANISH:
    romanization_method: NONE
    annotation_config:
      font_path: "fonts/ARIAL.TTF"
      font_size_ratio: 0.016
      buffer_size: 100
      color: [ 217, 95, 2 ]
      language_start_y_offset: 0.58
    background:
      family_tree: [ "Indo-European", "Italic", "Romance" ]
      alphabet: "Latin"
      sample_text: "El veloz murciélago hindú comía feliz cardillo y kiwi."

  ARABIC_LEVANTINE:
    romanization_method: ALA_LC
    annotation_config:
      font_path: "fonts/ARIAL.TTF"
      font_size_ratio: 0.0184
      buffer_size: 100
      color: [ 231, 41, 138 ]
      language_start_y_offset: 0.65
    background:
      family_tree: [ "Afro-Asiatic", "Semitic", "Central Semitic" ]
      alphabet: "Arabic"
      sample_text: "صِفْرٌ بَارِدٌ يَأْكُلُ خُبْزًا وَفَاكِهَةً طَيِّبَةً."

  CHINESE_MANDARIN_SIMPLIFIED:
    romanization_method: PINYIN
    annotation_config:
      font_path: "fonts/NotoSerifCJKsc-VF-Simplified-Chinese.ttf"
      font_size_ratio: 0.0168
      buffer_size: 100
      color: [ 157, 152, 219 ]
      language_start_y_offset: 0.76
    background:
      family_tree: [ "Sino-Tibetan", "Sinitic" ]
      alphabet: "Simplified Chinese characters"
      sample_text: "一只敏捷的棕色狐狸跳过一只懒狗。"
  HINDI:
    romanization_method: ISO_15919
    annotation_config:
      font_path: "fonts/NotoSansDevanagari-VariableFont.ttf"
      font_size_ratio: 0.016
      buffer_size: 100
      color: [ 257, 152, 219 ]
      language_start_y_offset: 0.86
    background:
      family_tree: [ "Indo-European", "Indo-Iranian", "Indo-Aryan" ]
      alphabet: "Devanagari"
      sample_text: "एक तेज़ भूरी लोमड़ी आलसी कुत्ते के ऊपर कूदती है।"
