name: Update Skellycam UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'skellysubs-ui/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version your project requires

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies and build
      working-directory: ./skellysubs-ui
      run: |
        pnpm install
        pnpm build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: skellysubs-ui-dist
        path: skellysubs-ui/dist